name: traceq
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - scipy
  - pandas
  - networkx
  - matplotlib
  - seaborn
  - qiskit
  - ipykernel
  - scikit-learn
  - pip:
      - -r traceq/pip-requirements.txt