name: traceq
channels:
  - defaults
  - gurobi
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.2.2=hbcca054_0
  - comm=0.2.1=pyhd8ed1ab_0
  - debugpy=1.6.7=py310heca2aa9_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - gurobi=11.0.0=py310_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.1=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py310hff52083_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libcxx=16.0.6=he02047a_2
  - libcxxabi=16.0.6=h4bc722e_2
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.41.2=h2797004_1
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libuuid=1.41.5=h5eee18b_0
  - libzlib=1.2.13=h4ab18f5_6
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.2.1=h4ab18f5_2
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=23.3.1=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.10.13=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pyzmq=25.1.2=py310h795f18f_0
  - readline=8.2=h8228510_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd8ed1ab_1
  - sqlite=3.41.2=h2c6b66d_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.3.3=py310h2372a71_1
  - traitlets=5.14.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.4.5=h5eee18b_0
  - zeromq=4.3.5=h75354e8_4
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - pip:
      - absl-py==2.0.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.6.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autograd==1.8.0
      - autoray==0.7.2
      - bqskit==1.2.1
      - bqskitrs==0.4.1
      - cachetools==5.3.2
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - contourpy==1.1.1
      - cryptography==42.0.2
      - cycler==0.12.1
      - cython==3.1.2
      - diastatic-malt==2.15.2
      - dill==0.4.0
      - easydict==1.13
      - flatbuffers==23.5.26
      - fonttools==4.43.1
      - frozenlist==1.7.0
      - future==1.0.0
      - gast==0.5.4
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grakel==0.1.10
      - grpcio==1.59.2
      - h5py==3.10.0
      - idna==3.4
      - ipywidgets==8.1.7
      - joblib==1.3.2
      - jupyterlab-widgets==3.0.15
      - keras==2.14.0
      - kiwisolver==1.4.5
      - lark==1.3.0
      - libclang==16.0.6
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.8.1
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - multidict==6.6.3
      - networkx==3.2.1
      - ntlm-auth==1.5.0
      - numpy==1.23.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pandas==2.3.1
      - pbr==5.11.1
      - pillow==10.1.0
      - ply==3.11
      - propcache==0.3.2
      - protobuf==4.25.0
      - psutil==5.9.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pydot==1.4.2
      - pygmtools==0.5.3
      - pygraphviz==1.14
      - pyjwt==2.8.0
      - pylatexenc==2.10
      - pyparsing==3.1.1
      - pyperclip==1.11.0
      - python-sat==1.8.dev24
      - pytz==2025.2
      - pyzx==0.9.0
      - qiskit==1.0.2
      - requests==2.31.0
      - requests-ntlm==1.1.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - rustworkx==0.17.1
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - scipy-openblas32==0.3.30.0.2
      - seaborn==0.13.2
      - stevedore==5.1.0
      - symengine==0.11.0
      - sympy==1.12
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tomlkit==0.13.3
      - tqdm==4.66.1
      - typing-extensions==4.8.0
      - tzdata==2025.2
      - urllib3==2.2.1
      - uv==0.9.5
      - websocket-client==1.7.0
      - websockets==12.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.14
      - wrapt==1.14.1
      - yarl==1.20.1
prefix: /home/george/miniconda3/envs/traceq
